<a href="https://colab.research.google.com/github/awellos/ExploreAI/blob/main/list%20slicing%20eigenvalues/vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LISTS


In [ ]:
Fruits = ["Mango", "Bananas", "Apple"]

In [ ]:
type(Fruits)

list

In [ ]:
Fruits [2] #positive indexing

'Apple'

In [ ]:
Fruits[-2] #negative indexing

'Bananas'

In [ ]:
Fruits[1] = "Avocado"
print(Fruits)

['Mango', 'Avocado', 'Apple']


# Slicing

In [ ]:
Fruits_list = ["mango","banana","apple","apple","grape","passion","pineapple"]

In [ ]:
#starting point: the end point (exclusive)
Fruits_list[2 : 5]

['apple', 'apple', 'grape']

In [ ]:
Fruits_list[4:]

['grape', 'passion', 'pineapple']

In [ ]:
Fruits_list[:5]

['mango', 'banana', 'apple', 'apple', 'grape']

In [ ]:
Fruits_list[:-5]

['mango', 'banana']

In [ ]:
Fruits_list[-2 :-]

[]

In [ ]:
import numpy as np
A = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
Lambda = np.diag(eigenvalues)
# Q contains the eigenvectors
Q = eigenvectors
Q_inv = np.linalg.inv(Q)
A_reconstructed = Q @ Lambda @ Q_inv
# Display results print("Original Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors Q:")
print(Q)
print("\nDiagonal Matrix Lambda:")
print(Lambda)
print("\nReconstructed Matrix:")
print(np.round(A_reconstructed, 6))

[[2 1]
 [1 2]]

Eigenvalues:
[3. 1.]

Eigenvectors Q:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Diagonal Matrix Lambda:
[[3. 0.]
 [0. 1.]]

Reconstructed Matrix:
[[2. 1.]
 [1. 2.]]
